# Convenience only. The source of truth for every check is pyproject.toml plus
# .github/workflows/ci.yml — CI does not run `make`, so these targets are kept to
# single obvious commands that mirror the CI steps exactly.
#
# What the skip-hole fix changed here (full story in the ci.yml header):
#
#   * `install` now installs .[checkpoint,dev]: the [checkpoint] extra carries
#     torch, and without it 41 tests skip (387 passed with torch; 346 passed /
#     41 skipped without — CI's old green). pytest-cov rides along because the
#     `test` command carries coverage flags, exactly like CI's step.
#   * `test` mirrors CI's pytest invocation, coverage floor included.
#   * FS_FORBID_SKIPS is the ONE declared divergence from CI: the `check` job
#     sets it job-wide so any skip fails the build; `make test` leaves it unset
#     so a laptop may skip — but tests/conftest.py still names every skip and
#     its reason in the summary. To run the suite byte-for-byte as CI sees it:
#
#         FS_FORBID_SKIPS=1 make test
#
#   * `skip-guard-probe` mirrors CI's probe step: it generates a deliberately
#     skipped test and asserts the armed guard fails the run AND names it. It is
#     a compound recipe rather than "one obvious command" — the CI step is a
#     script, and the faithful mirror of a script is the same script. Dropping
#     it from `make check` would make `check` weaker than CI, which is its own
#     vacuous pass, so fidelity won over brevity here.
#   * `mutation` mirrors the mutation job (~2 min; a surviving mutant fails it).

.PHONY: install test lint fmt typecheck controls mutation skip-guard-probe check clean

install:
	pip install -e ".[checkpoint,dev]" "pytest-cov>=5" --extra-index-url https://download.pytorch.org/whl/cpu

test:
	pytest --cov=foundationscale --cov-report=term-missing --cov-fail-under=90

lint:
	ruff check src tests tools
	ruff format --check src tests tools

fmt:
	ruff check --fix src tests tools
	ruff format src tests tools

# Run this in the SAME environment as `install` creates — one with [checkpoint].
# mypy without torch checks a different program: MetadataIndex becomes Any, and an
# `Any | None` assigned over a variable already bound to `str` stops being an error.
# A torch-free typecheck passed this tree; CI, which installs torch, failed it on all
# three Pythons. Same command, same source, different answer, because the environment
# differed. That is the repository's own thesis pointed at its Makefile.
typecheck:
	mypy src

controls:
	python -m foundationscale.gates.controls

mutation:
	FS_FORBID_SKIPS=1 python tools/mutate.py

skip-guard-probe:
	@printf '%s\n' \
		'"""Throwaway MUST_FIRE probe for the FS_FORBID_SKIPS guard (tests/conftest.py).' \
		'' \
		'Generated by the skip-guard-probe target and deleted by it. If this file ever' \
		'survives into the real suite run, the armed guard fails the build on its skip.' \
		'"""' \
		'' \
		'import pytest' \
		'' \
		'' \
		'def test_skip_guard_probe():' \
		'    pytest.skip("deliberate skip; an armed skip guard must fail this run")' \
		> tests/test__skip_guard_probe.py
	@set +e; \
	output=$$(FS_FORBID_SKIPS=1 pytest tests/test__skip_guard_probe.py 2>&1); \
	rc=$$?; \
	set -e; \
	printf '%s\n' "$$output"; \
	rm -f tests/test__skip_guard_probe.py; \
	if [ $$rc -eq 0 ]; then \
		echo "skip-guard-probe: FAILED - guard armed but a skipped test exited 0"; \
		exit 1; \
	fi; \
	printf '%s\n' "$$output" | grep -q test_skip_guard_probe || { \
		echo "skip-guard-probe: FAILED - run failed without the guard naming the probe"; \
		exit 1; \
	}; \
	echo "skip-guard-probe: guard fired and named its probe, as CI requires"

check: lint typecheck skip-guard-probe test controls mutation

clean:
	rm -rf build dist .eggs src/*.egg-info *.egg-info \
		.pytest_cache .mypy_cache .ruff_cache .cache \
		.coverage .coverage.* coverage.xml htmlcov
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
