#!/usr/bin/env python3
"""#134: the training-bounds guard reads the FLAG, so every env-sourced launch refuses.

MEASURED by the entrypoint's own --selftest inside the container: row 1
`env_contract_complete` (MUST_PASS) failed with "training bounds must be greater than
zero" while all six MUST_FIRE rows fired correctly -- 9 of 10 rows matched, verdict
SELFTEST_FAIL. A MUST_PASS row that fails weakens every other row in the battery, so this
had to be root-caused rather than waived.

The guard is:

    if int(args.iteration_budget or 0) <= 0 or int(args.early_save_steps or 0) <= 0:
        # Source-bearing parsing already reports this when a value came from env.
        raise ContractError("training bounds must be greater than zero")

`args.iteration_budget` is the command-line FLAG. Both bounds are resolved by
`_sourced(..., positive_int)` from flag-OR-env, and the launcher supplies them as
FS_ITERATION_BUDGET / FS_EARLY_SAVE_STEPS in the ENVIRONMENT. On every env-sourced launch
the flag is None -> `or 0` -> 0 -> refusal. The entrypoint could only ever have started
when both bounds were passed as explicit flags, which is not how the launcher calls it.

WHY DELETE RATHER THAN REPAIR. The first version of this patch folded both bounds into
the sourced-value loop above, on the theory that argparse's `type=int` admits negatives
and so the flag path would otherwise be unguarded. The control battery REFUTED that: the
container run returned "iteration_budget from flag is invalid: expected an integer >= 1",
which comes from `_sourced` itself. Reading it confirms the mechanism -- `_sourced`
special-cases these two names and runs the parser on the flag branch as well as the env
branch. So `positive_int` (minimum=1) already covers BOTH sources, the folded-in loop
entries were unreachable, and the honest fix is to remove the broken check and nothing
else. That precondition is load-bearing, so C3 below pins it: if the flag-branch parse is
ever removed, this stage goes red instead of silently deleting the last guard.

This is a patch stage, not a hand edit: h100/gen/fs_train.fixed.py is generated by
extract_fs_train.py on every build, so a hand edit would be silently reverted.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import subprocess
import sys
import tempfile

ANCHOR = """    if int(args.iteration_budget or 0) <= 0 or int(args.early_save_steps or 0) <= 0:
        # Source-bearing parsing already reports this when a value came from env.
        raise ContractError("training bounds must be greater than zero")
"""

REPLACEMENT = """    # #134: a check on args.iteration_budget / args.early_save_steps stood here. It read
    # the FLAG, not the resolved flag-or-env value, so every env-sourced launch -- which
    # is how the launcher calls this -- saw 0 and refused. Removed rather than repaired:
    # _sourced() runs positive_int (minimum=1) on BOTH the env and the flag branch for
    # these two names, so the property is already enforced at parse time with the source
    # named in the message. Re-adding a check here would be unreachable code.
"""

# The precondition the deletion rests on. If this disappears, the deletion becomes
# unsafe, so the stage must refuse rather than apply.
PRECONDITION = """        if name in {"iteration_budget", "early_save_steps"}:
            try:
                value = parser(str(value))"""

SENTINEL = "#134: a check on args.iteration_budget"


def apply(text: str) -> tuple[str, bool]:
    """Return (new_text, changed). Idempotent: already-patched input is returned as-is."""
    if SENTINEL in text:
        return text, False
    patched = text.replace(ANCHOR, REPLACEMENT)
    return patched, patched != text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    args = ap.parse_args()
    target = pathlib.Path(args.root) / "h100" / "gen" / "fs_train.fixed.py"

    original = target.read_text(encoding="utf-8")
    if SENTINEL in original:
        print(f"already applied: {target} carries the #134 deletion")
        return 0

    gates: list[tuple[str, bool, str]] = []
    n = original.count(ANCHOR)
    gates.append(("C1 flag-only check occurs exactly once", n == 1, f"found {n}"))
    gates.append(
        ("C2 both bounds are parsed with positive_int",
         original.count("positive_int,") == 2, f"{original.count('positive_int,')} call site(s)")
    )
    gates.append(
        ("C3 PRECONDITION: _sourced parses the flag branch for these two names",
         PRECONDITION in original,
         "" if PRECONDITION in original else "ABSENT -- deleting would remove the last guard")
    )
    if not all(ok for _, ok, _ in gates):
        _report(gates)
        return 2

    patched, changed = apply(original)
    gates.append(("C4 text changed", changed, ""))
    gates.append(("C5 sentinel present exactly once", patched.count(SENTINEL) == 1, ""))
    gates.append(
        ("C6 no reader of the raw flag survives",
         "args.iteration_budget or 0" not in patched
         and "args.early_save_steps or 0" not in patched, "")
    )
    # Adjacent properties this edit must not disturb: they are different rules.
    gates.append(
        ("C7 ordering rule preserved",
         patched.count("early_save_steps must be less than iteration_budget") == 1, "")
    )
    gates.append(
        ("C8 log_every rule preserved",
         patched.count("log_every cannot exceed iteration_budget") == 1, "")
    )
    again, changed_again = apply(patched)
    gates.append(("C9 re-application is a no-op", (not changed_again) and again == patched, ""))

    if not all(ok for _, ok, _ in gates):
        _report(gates)
        return 3

    fd, tmp = tempfile.mkstemp(dir=str(target.parent), suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(patched)
    os.replace(tmp, target)

    proc = subprocess.run(
        [sys.executable, "-m", "py_compile", str(target)], capture_output=True, text=True
    )
    ok = proc.returncode == 0
    gates.append(("C10 py_compile clean", ok, proc.stderr.strip()[:160]))
    if not ok:
        target.write_text(original, encoding="utf-8")
        _report(gates)
        print("restored original bytes; an unverified artifact is not left in place", file=sys.stderr)
        return 4

    _report(gates)
    print(
        f"patched {target}: flag-only bounds check removed; "
        f"byte delta {len(patched) - len(original):+d}; py_compile: clean"
    )
    return 0


def _report(gates: list[tuple[str, bool, str]]) -> None:
    print("gate table:")
    for label, ok, note in gates:
        print(f"  {label}: {'PASS' if ok else 'FAIL'}{(' (' + note + ')') if note else ''}")


if __name__ == "__main__":
    raise SystemExit(main())
