#!/usr/bin/env python3
"""Apply the singularity splice to fs_container_backend.sh, and PROVE it.

The point of splicing rather than regenerating is that the enroot arm cannot
be damaged. That is only true if the splice is checked, so this refuses to
write unless every gate below passes. Each gate names the specific way a
splice can look successful while having destroyed something:

  G1 every function present before is present after      (a replacement whose
     body was truncated mid-brace silently swallows the next function)
  G2 the enroot reference count does not DROP            (the whole failure
     mode that killed the first attempt: 50 -> 16, still valid bash)
  G3 the result passes `bash -n`                         (syntax)
  G4 each replacement body actually defines the function it claims
  G5 the singularity arm is really present               (a splice that
     applied cleanly but added nothing is a vacuous success)
  G6 no credential-shaped literal enters the file        (the reference impl
     this work is modelled on hardcodes a live W&B key; do not inherit that)
  G7 every fs_* function CALLED is DEFINED               (the composition gate)

G7 exists because G1-G6 all passed a splice that was broken. The four bodies
were generated by four parallel workers who never saw each other; the pinned
vocabulary told each of them to CALL fs_env_forward_allowlisted and
fs_assert_torch_provenance, and the dispatch partitioned work by EXISTING
function -- so the two NEW helpers had no owner and every worker assumed
another had written them. MEASURED: 3 call sites, 0 definitions.

`bash -n` cannot catch this. Bash resolves function names at CALL time, so an
undefined function is a syntactically perfect script that returns 127. The
consequence depends only on the caller's punctuation:

    fs_env_forward_allowlisted "$v" || continue     # 127 -> skip EVERY var,
                                                    # container gets nothing,
                                                    # silently, no error
    fs_assert_torch_provenance "$f" || fs_die ...   # 127 -> always fatal,
                                                    # arm permanently blocked

One silently wrong, one permanently blocked, neither visible to a syntax
check. A gate that says "the splice applied cleanly" without G7 is measuring
the splice mechanism and calling it a verdict on the splice.

Counts are reported as "before -> after" with denominators, never as "ok".
Writes to a NEW path by default; --in-place only after you have read the diff.
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile

# Resolved from --root like every other stage. Absolute build-host paths were baked in
# here until #136: this file produces the backend's 73 KB base text, so a hardcoded path
# made the whole build plane non-relocatable -- the #123 defect class one layer up, in the
# one stage whose output every later backend stage consumes.
#
# --repo names the upstream tree the base text is spliced FROM.
#
# #156: the default used to be the single guess `_ROOT.parent / "fs-repo"`, which encodes
# one directory layout -- the plane checked out BESIDE the framework repo, and that repo
# named "fs-repo". Both halves are assumptions about somebody's disk, and the second is an
# assumption about somebody's naming. Measured: publishing the plane INSIDE the repo (the
# arrangement a reader gets from `git clone`) makes the guess resolve to <repo>/fs-repo,
# which does not exist, and every build goes red at this stage. The build was green here
# only because of an adjacency that was never stated anywhere -- which is to say it was
# reproducible on one machine.
#
# So resolution is now MEASURED rather than assumed: a candidate is the upstream only if
# the file this stage actually needs is present under it. Candidates are tried in order of
# how explicit they are, and every one that was tried is named in the refusal, because a
# resolver that fails without saying where it looked sends the reader to guess in turn.
def _arg(flag: str, default=None):
    return sys.argv[sys.argv.index(flag) + 1] if flag in sys.argv else default


_ROOT = pathlib.Path(_arg("--root", ".")).resolve()
_NEEDLE = pathlib.Path("launchers") / "fs_container_backend.sh"


def _repo_candidates(root: pathlib.Path):
    """(label, path) pairs, most explicit first. Ancestors cover the plane living at any
    depth inside the framework repo; the trailing named sibling preserves the historical
    layout so an existing checkout keeps working."""
    flag = _arg("--repo")
    if flag:
        yield "--repo", pathlib.Path(flag).resolve()
    env = os.environ.get("FS_UPSTREAM_REPO")
    if env:
        yield "$FS_UPSTREAM_REPO", pathlib.Path(env).resolve()
    for anc in [root, *root.parents]:
        yield "ancestor of --root", anc
    yield "legacy sibling", root.parent / "fs-repo"


_tried, _REPO = [], None
for _label, _cand in _repo_candidates(_ROOT):
    _tried.append(f"{_cand}  ({_label})")
    if (_cand / _NEEDLE).is_file():
        _REPO = _cand
        break

if _REPO is None:
    _seen, _uniq = set(), []
    for _t in _tried:
        if _t not in _seen:
            _seen.add(_t)
            _uniq.append(_t)
    # #161: REFUSE is 96. `raise SystemExit("text")` prints the text and exits 1,
    # which the build reads as an ordinary stage failure.
    print(
        "apply_splice: upstream backend not found. No candidate contains "
        f"{_NEEDLE}.\n"
        + "".join(f"  tried: {t}\n" for t in _uniq)
        + "  Point at the framework repo with --repo <path> or $FS_UPSTREAM_REPO.\n"
        "  This stage splices the SHIPPED backend's base text; without the upstream "
        "source there is nothing to splice, and continuing would leave the previous "
        "spliced.sh in place and let the build certify a stale backend (#136).",
        file=sys.stderr,
    )
    raise SystemExit(96)

SRC = _REPO / _NEEDLE
print(f"apply_splice: upstream repo resolved to {_REPO} (candidates tried: {len(_tried)})")
SPLICE = _ROOT / "h100" / "backend_splice.json"
DST = _ROOT / "h100" / "gen" / "fs_container_backend.spliced.sh"

sys.path.insert(0, str(_ROOT))
from h100_backend_splice import functions  # noqa: E402  -- shared brace matcher

CRED = re.compile(r"""(?ix)
    (api[_-]?key|secret|token|password|passwd)\s*=\s*["']?[A-Za-z0-9_\-]{16,}
  | \b[0-9a-f]{40}\b
""")


def main() -> int:
    if not SPLICE.exists():
        print(f"REFUSING: {SPLICE} absent — nothing to apply", file=sys.stderr)
        return 3
    rows = json.loads(SPLICE.read_text("utf-8"))
    if not rows or not rows[0].get("ok"):
        print(f"REFUSING: splice task failed: {rows[0].get('error') if rows else 'empty'}",
              file=sys.stderr)
        return 3
    spec = json.loads(rows[0]["content"])

    before = SRC.read_text("utf-8")
    fmap_before = functions(before)
    enroot_before = len(re.findall(r"enroot", before))

    text = before
    applied: list[str] = []
    # Replacements are applied one at a time, re-locating the function each
    # time: offsets from a single up-front scan go stale the moment the first
    # body changes length, and using them anyway corrupts the file in a way
    # that still parses.
    for r in spec.get("replacements", []):
        name, body = r["function"], r["body"]
        fmap = functions(text)
        if name not in fmap:
            print(f"REFUSING: replacement target {name!r} not in file", file=sys.stderr)
            return 4
        if not functions(body).get(name):
            print(f"REFUSING: replacement body for {name!r} does not define {name}",
                  file=sys.stderr)                                          # G4
            return 4
        s, e = fmap[name]
        text = text[:s] + body.rstrip() + text[e:]
        applied.append(f"replace {name}")

    for a in spec.get("additions", []):
        name, body, after = a["name"], a["body"], a["after"]
        fmap = functions(text)
        if name in fmap:
            print(f"REFUSING: addition {name!r} already exists", file=sys.stderr)
            return 4
        if after not in fmap:
            print(f"REFUSING: anchor {after!r} for addition {name!r} not found",
                  file=sys.stderr)
            return 4
        e = fmap[after][1]
        text = text[:e] + "\n\n" + body.rstrip() + text[e:]
        applied.append(f"add {name} after {after}")

    fmap_after = functions(text)
    enroot_after = len(re.findall(r"enroot", text))
    sing_after = len(re.findall(r"(?i)singularity|apptainer", text))
    lost = sorted(set(fmap_before) - set(fmap_after))

    ok = True
    print(f"functions : {len(fmap_before)} -> {len(fmap_after)}")
    if lost:                                                                # G1
        print(f"  FAIL G1  lost {len(lost)} of {len(fmap_before)}: {lost}"); ok = False
    else:
        print(f"  PASS G1  all {len(fmap_before)} preserved")
    print(f"enroot refs: {enroot_before} -> {enroot_after}")
    if enroot_after < enroot_before:                                        # G2
        print(f"  FAIL G2  DROPPED {enroot_before - enroot_after}"); ok = False
    else:
        print(f"  PASS G2  none of {enroot_before} lost")
    if sing_after < 5:                                                      # G5
        print(f"  FAIL G5  only {sing_after} singularity refs — splice added nothing")
        ok = False
    else:
        print(f"  PASS G5  {sing_after} singularity refs present")
    creds = [m.group(0)[:24] for m in CRED.finditer(text)]
    creds = [c for c in creds if c not in {m.group(0)[:24] for m in CRED.finditer(before)}]
    if creds:                                                               # G6
        print(f"  FAIL G6  {len(creds)} new credential-shaped literal(s)"); ok = False
    else:
        print("  PASS G6  no new credential-shaped literals")

    # G7 -- every fs_* function called must be defined. Comments are stripped
    # first: the bodies DISCUSS these helpers in prose, and counting a mention
    # as a definition is how this gate would learn to pass itself.
    nocomment = re.sub(r"(?m)^\s*#.*$", "", text)
    called: dict[str, int] = {}
    # re.M is load-bearing, not decoration. Without it `^` anchors only at
    # offset 0, so a call sitting at the start of ANY other line is invisible
    # and the gate reports a smaller number with total confidence. Measured:
    # the flagless version found 3 undefined helpers and silently missed
    # fs_assert_torch_provenance, whose call site is line-initial. That is the
    # same false-negative shape this gate exists to catch -- a detector that
    # cannot match reports zero and reads exactly like clean.
    for m in re.finditer(
        # The trailing lookahead rejects ASSIGNMENTS. `|| fs_drill_ssh_n=$((n+1))`
        # and `fs_guard_seen="${SLURM_JOB_NODELIST:-}"` sit in command position and
        # are not calls; without this the gate reported 6 undefined helpers when 2
        # were real, and over-reporting discredits a gate exactly as fast as
        # under-reporting does. Both directions were measured before this shipped.
        r"(?:^|\|\||&&|;|\||\$\(|`|\bthen\b|\belse\b|\bdo\b|!)[ \t]*"
        r"(fs_[a-z0-9_]+)\b(?!\s*(?:\+?=|\[))",
        nocomment,
        re.M,
    ):
        called[m.group(1)] = called.get(m.group(1), 0) + 1
    undefined = {k: v for k, v in called.items() if k not in fmap_after}
    print(f"fs_* calls : {len(called)} distinct, {len(fmap_after)} function(s) defined")
    if undefined:                                                           # G7
        ok = False
        print(f"  FAIL G7  {len(undefined)} called but NEVER defined "
              f"(bash resolves at call time; `bash -n` cannot see this):")
        for k, v in sorted(undefined.items()):
            print(f"             {k}  ({v} call site(s)) -> returns 127 at runtime")
    else:
        print(f"  PASS G7  all {len(called)} called fs_* function(s) are defined")

    with tempfile.NamedTemporaryFile("w", suffix=".sh", delete=False) as fh:
        fh.write(text)
        tmp = fh.name
    rc = subprocess.run(["bash", "-n", tmp], capture_output=True, text=True)
    if rc.returncode != 0:                                                  # G3
        print(f"  FAIL G3  bash -n: {rc.stderr.strip()[:300]}"); ok = False
    else:
        print("  PASS G3  bash -n clean")

    print("applied   : " + "; ".join(applied) if applied else "applied   : NOTHING")
    if not applied:
        print("  FAIL     an empty splice is not a successful one"); ok = False
    if spec.get("gaps"):
        print(f"gaps      : {spec['gaps'][:700]}")

    if not ok:
        print("\nREFUSING TO WRITE — gates above are red", file=sys.stderr)
        return 5
    dst = SRC if "--in-place" in sys.argv else DST
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(text, "utf-8")
    print(f"\nALL GATES GREEN -> {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
